name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2 - Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3 - Cache Maven packages
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4 - Build with Maven
      - name: Build & Run Tests
        run: mvn clean test -B

      # Step 5 - Upload Test Report (Extent/HTML)
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ExtentReport
          path: target/ExtentReports/  # adjust path to your extent.html
